### ISSUE TITLE
Getting "'int' object has no attribute 'tzinfo'" while editing an object

### ISSUE THREAD

**Issue by ghost** [Niklas9/django-unixdatetimefield#3]
Hello

While editting objects with the unixdatetimefield in the admin site I get the following error.

```
'int' object has no attribute 'tzinfo'
```

In the templates the field displays just as an integer, not date.

This is a bit of code from my model showing the unixdatetimefield definition.

```
lastvisit = UnixDateTimeField(db_column='lastVisit',
        verbose_name=_('ostatnia wizyta'), null=True, blank=True)
```

My Django version is 1.8.3. Could you help me to fix it, please? Thanks.

**Comment by Niklas9** [comment]
this has been fixed now - https://github.com/Niklas9/django-unixdatetimefield/commit/07f0a48c4aaa5b8f1aa450ae839121e0f3d90a37, submitted new version 0.1.4 to pip as well!

**Comment by juliocarrera** [comment]
Has this fix been ported to Django 1.10?

**Comment by Niklas9** [comment]
Yes @juliocarrera, are you experiencing a problem with 1.10 with this?

**Comment by juliocarrera** [comment]
No, I'm not. I thought I was but the root problem was that I was not closing the database connection before forking a process. Everything is good now. Thanks for following up.

**Comment by Niklas9** [comment]
Okay cool, np 👍
