### ISSUE TITLE
'int' object has no attribute 'utcoffset' when browsing admin on Django 1.9.1

### ISSUE THREAD

**Issue by LondonAppDev** [Niklas9/django-unixdatetimefield#4]
When using Django admin with Django 1.9.1 you get a `'int' object has no attribute 'utcoffset'` when trying to view a model field using the UnixDateTimeField.

**Comment by Niklas9** [comment]
Thanks, will look into this asap @LondonAppDev

**Comment by Niklas9** [comment]
this has been fixed now @LondonAppDev  - https://github.com/Niklas9/django-unixdatetimefield/commit/07f0a48c4aaa5b8f1aa450ae839121e0f3d90a37, submitted new version 0.1.4 to pip as well!
