### ISSUE TITLE
Admin list filter

### ISSUE THREAD

**Issue by kudlatyamroth** [Niklas9/django-unixdatetimefield#5]
When You add this field to filters in admin, and want to filter last 7 days for example,
you get error:

`could not convert string to float: '2016-11-25 00:00:00+00:00'`

in url:
`?add_date__gte=2016-11-17+00%3A00%3A00%2B00%3A00&add_date__lt=2016-11-25+00%3A00%3A00%2B00%3A00`

**Comment by Niklas9** [comment]
Thanks for reporting, I'll look into it asap

**Comment by Niklas9** [comment]
Just fixed this and published a new release, 0.1.5, https://pypi.python.org/pypi/django-unixdatetimefield/0.1.5.

Let me know if you find any other issues! Thanks for filing.

**Comment by Niklas9** [comment]
Closing..

**Comment by kudlatyamroth** [comment]
thanks :)
if i find anything, ofc i will fill issue :)
